/*  Program:     Blood Drive File
    Author:      Selina Arjomand
    Class:	     CSCI 110 MW
    Date:	     11/11/20
    Description: The program usese files to take in the number of 
                 pints donated during the drive. The program then
                 calculates the average, highest, and lowest
                 number of pints donanted. 

    I certify that the code below is my own work.
	
	Exception(s): N/A
*/

#include <iostream>
#include <string>
#include <iomanip> //to set decimal precision
#include <cstdlib> //to use random function
#include <ctime> //to get diff results for random fuction
#include <cmath> //to use library math functions
#include <fstream> //for files

using namespace std;

void getPints(double pints[], int &count);
double getAverage(double pints[], int hours);
double getHigh(double pints[], int hours);
double getLow(double pints[], int hours);
void displayInfo(int hours, double averagePints, double highPints, double lowPints);

const int MAX_HOURS = 24;
int main()
{
    cout << "Author: Selina Arjomand\n";

	//Declare local variables
	double pints[MAX_HOURS];
	int hours;
	double avePints, highPints, lowPints;
		
	getPints(pints, hours);
	cout << "hours: " << hours << endl;
    	cout << "first value: " << pints[0] << endl;
    	cout << "last value:  " << pints[hours - 1] << endl;
	avePints = getAverage(pints, hours);
	highPints = getHigh(pints, hours);
	lowPints = getLow(pints, hours);
	displayInfo(hours, avePints, highPints, lowPints);

}

void getPints(double pints[], int &count){
    ifstream bloodInFile;
    count = 0;
    int value;

    bloodInFile.open("bloodDrive.txt");
    if (!bloodInFile)
    {
        cout << "Error opening file for input. Stop program now." << endl;
        return;
    }
	
    bloodInFile >> value;
    while(!bloodInFile.eof())
    {
        pints[count] = value;
        count++;
        bloodInFile >> value;
    }
    bloodInFile.close();
}

double getAverage(double pints[], int hours){
	int counter;
	double totalPints = 0;
	double averagePints;
    for (counter = 0; counter < hours; counter++)
    {
        totalPints = totalPints + pints[counter];
    }

    averagePints = totalPints / counter;
    return averagePints;
}

double getHigh(double pints[], int hours){
    int counter;
    double highest = pints[0];

    for (counter = 0; counter < hours; counter++)
    {
        if (pints[counter] > highest)
        {
            highest = pints[counter];
        }
    }
    return highest;
}

double getLow(double pints[], int hours){
    int counter;
    double lowest = pints[0];

    for (counter = 0; counter < hours; counter++)
    {
        if (pints[counter] < lowest)
        {
            lowest = pints[counter];
        }
    }
    return lowest;
}


void displayInfo(int hours, double averagePints, double highPints, double lowPints){
    ofstream bloodOutFile;
	bloodOutFile.open("bloodResults.txt");

    bloodOutFile << "Report generated by Selina Arjomand" << endl;

    bloodOutFile << "Blood drive period: ";
    cout << fixed << showpoint << setprecision(1);
    bloodOutFile << hours << endl;
    bloodOutFile << "Average Pints: ";
    bloodOutFile << averagePints << endl;
    bloodOutFile << "Highest Pints: ";
    bloodOutFile << highPints << endl;
    bloodOutFile << "Lowest Pints: ";
    bloodOutFile << lowPints << endl;

	bloodOutFile.close();
}
