/*  Program:     Lab Final Question 2
    Author:      Selina Arjomand
    Class:	     CSCI 110 MW
    Date:	     12/09/20
    Description: The program puts and array in descending order
                 and outputs it to a file. 

    I certify that the code below is my own work.
	
	Exception(s): N/A
*/

#include <iostream>
#include <string>
#include <iomanip> //to set decimal precision
#include <cstdlib> //to use random function
#include <ctime> //to get diff results for random fuction
#include <cmath> //to use library math functions
#include <fstream> //for files

using namespace std;


void bubbleSort(int arr[], int n);
void swap(int &a, int &b);
void printList(int arr[], int n);

const int MAX = 10;
int main()
{
    int arr[MAX] = {5, 3, 6, 7, 1, 9, 0, 8, 1, 4};

    int index = 0;
    while (index < MAX-1)
    {
        bubbleSort(arr, MAX);
        index++;
    }

    printList(arr, MAX);

    return 0;

}

void bubbleSort(int arr[], int n){
    for (int i = 0; i < n-1; i++)
    {
        if (arr[i] < arr[i+1])
        {
            swap(arr[i], arr[i+1]);
        }
    }   
}

void swap(int &a, int &b){
    int temp = a;
    a = b;
    b = temp;
}

void printList(int arr[], int n){
    ofstream outFile;
	outFile.open("problem2.txt");

    outFile << "Generated by Selina Arjomand" << endl;

    int index = 0;
    while (n > 0)
    {
        for (int i = 0; i < 4; i++)
        {
            if (n > 0)
            {
                outFile << arr[index] << "     ";
                index++;
                n--;
            }
        }
        outFile << endl;
    }
    outFile.close();
}
